# Generated by Django 4.2.7 on 2023-12-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
