# Generated by Django 4.2.7 on 2023-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_shift_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
