# Generated by Django 4.2.7 on 2023-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='invoice_num',
            field=models.IntegerField(null=True),
        ),
    ]
