# Generated by Django 4.2.7 on 2023-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_provider_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='logo',
            field=models.ImageField(blank=True, default='sie7e.png', null=True, upload_to=''),
        ),
    ]
