# Generated by Django 5.0 on 2023-12-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
