# Generated by Django 5.0 on 2024-02-27 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shifts',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='invoice_num',
        ),
        migrations.AddField(
            model_name='shift',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provided', to='security.invoice'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('wages', models.FloatField()),
                ('ss', models.FloatField()),
                ('irpf', models.FloatField()),
                ('gestoria', models.FloatField()),
                ('performance_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_provider', to='security.provider')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance', to='security.performance'),
        ),
    ]
