# Generated by Django 5.0 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_remove_invoice_shifts_remove_shift_invoice_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('performance_provider', 'month', 'year')},
        ),
    ]
