# Generated by Django 5.0 on 2024-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_performance_year_alter_performance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='gestoria',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='irpf',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ss',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='wages',
            field=models.FloatField(null=True),
        ),
    ]
