# Generated by Django 5.0 on 2024-02-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_alter_performance_gestoria_alter_performance_irpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='wages',
            new_name='income',
        ),
    ]
