# Generated by Django 5.0 on 2023-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bg_image',
            field=models.ImageField(blank=True, default='sie7e.png', null=True, upload_to='images/portfolio/'),
        ),
    ]
