# Generated by Django 5.0 on 2023-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.CharField(default='', max_length=200),
        ),
    ]
