# Generated by Django 5.0 on 2024-03-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('f_inicio', models.DateField(default=None)),
                ('f_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=100)),
                ('fumador', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('transito_intestinal_normal', models.BooleanField(default=False)),
                ('hidratacion', models.CharField(choices=[('Más de 1,5 litros diarios', 'Más de 1,5 litros diarios'), ('Menos de 1,5 litros diarios', 'Menos de 1,5 litros diarios')], max_length=100)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('tratamientos', models.TextField(blank=True, null=True)),
                ('habitos', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('altura', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_proxima', models.DateField(default=None, null=True)),
                ('peso', models.FloatField(null=True)),
                ('contorno_cintura', models.FloatField(null=True)),
                ('contorno_cadera', models.FloatField(null=True)),
                ('grasa_corporal', models.FloatField(null=True)),
                ('IMC', models.FloatField(null=True)),
                ('desayuno', models.TextField(blank=True, null=True)),
                ('media_manana', models.TextField(blank=True, null=True)),
                ('almuerzo', models.TextField(blank=True, null=True)),
                ('merienda', models.TextField(blank=True, null=True)),
                ('cena', models.TextField(blank=True, null=True)),
                ('post_cena', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_revision', to='diets.cliente')),
            ],
        ),
    ]
